apiVersion: v1
kind: Service
metadata:
  annotations: {}
  labels:
    app: rs23ff4335d
    applicationId: app_903fd815-63ed-4ad4-b9fd-9e3a3108feaf
    version: v0.0.1
  name: rs23ff4335d
spec:
  selector:
    app: rs23ff4335d
