apiVersion: v1
kind: Service
metadata:
  annotations: {}
  labels:
    app: rs23ff43ddd35d
    applicationId: app_cf4d596d-d1e3-47e5-92bf-dcdde349af83
    version: v0.0.1
  name: rs23ff43ddd35d
spec:
  selector:
    app: rs23ff43ddd35d
