apiVersion: v1
kind: Namespace
metadata:
  name: asdasdasd-dev
  labels:
    environment-id: env_284d1f50-7751-43c4-824b-d59f33a8432d
    project-id: project_b02f2e4b-f4c1-450a-ab69-21ec01685acd
    project-name: gittesting-project
    environment-name: dev
    organization-id: org_8866a8dc-875d-4215-82e6-928512b4c6ff
