apiVersion: autoscaling/v2beta1
kind: HorizontalPodAutoscaler
metadata:
  annotations: {}
  name: rs23ffss4335
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: rs23ffss4335
