apiVersion: autoscaling/v2beta1
kind: HorizontalPodAutoscaler
metadata:
  annotations: {}
  name: rs23ff43fff35d
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: rs23ff43fff35d
